image: docker:latest
services:
  - docker:dind

stages:
  - build
  - sync
  
build:
  image: maven:3-jdk-11
  stage: build
  except:
    - tags
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - "mvn clean install package deploy -B"
  artifacts:
    paths:
      - 'pom.xml'
      - '*/pom.xml'
      - '*/target/*.jar'
      - '*/target/*.app'
      - '*/target/*.tar.gz'
      - '*/target/*.sql'

release:
  image: maven:3-jdk-11
  stage: build
  only:
    - tags
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - "mvn versions:set -DnewVersion=$CI_COMMIT_TAG -B"
    - "mvn clean install package deploy -B"
  artifacts:
    paths:
      - 'pom.xml'
      - '*/pom.xml'
      - '*/target/*.jar'
      - '*/target/*.app'
      - '*/target/*.tar.gz'
      - '*/target/*.sql'

sync:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: sync
  script:
    - 'git checkout $CI_COMMIT_REF_NAME'
    - 'git status'
    - 'git remote remove github'
    - 'git remote add github "https://intrbiz:${GITHUB_PASS}@github.com/intrbiz/hs110.git"'
    - 'git push --tags github $CI_COMMIT_REF_NAME'
